### ISSUE TITLE
ToDo list for 1.0.3.

### ISSUE THREAD

**Issue by mzhukov1973** [mzhukov1973/gogs-creeping-madness-injector#2]
### ToDo for version 1.0.3:
- [x] Fix the [issue](https://github.com/mzhukov1973/gogs-creeping-madness-injector/issues/1) with **`LongHours UI mod`** menu item in `.../user/settings` being not clickable if **`SSH Keys`** item is currently selected.
- [x] Include javascript.svg logo icon with the mod installation set, amend installation instructions accordingly.
- [ ] Add a quick-settings menu drop-up into the standard [Gogs](https://github.com/gogits/gogs) footer.
- [ ] Fill the settings page itself with properly named and annotated (even if yet unconnected) controls to set mod's parameters. Use either exactly the elements found in other settings pages or use [Semantic](https://semantic-ui.com) (for now use version 2.3.1, later - guess it from the active [Gogs](https://github.com/gogits/gogs) installation itself).
- [ ] Add a general enable/disable control to the `.../user/settings` page, to control if **LongHours** is to run at all upon injection and properly connect it to the data - this one control should be completely functional.
- [ ] Make this JS logo change appearance to further indicate injections' status (i.e. ```not present```, ```loaded```, ```active```, ```error(?)```, ```disabled```, ```waiting to go active```, ```modified settings```, ```original settings```) and add the same status as text popup, appearing on hover over the settings item.
- [ ] In order to avoid depending on any external framework or library as well as for general lightness of code implement two-way coupling between settings values stored in global object's properties and UI controls for setting them, as found on `.../user/settings` page. Do so, by creating a proxy for the object with handler monitoring `.set(...)` calls and informing all concerned parties of any changes via custom events.
- [ ] Implement some simple client-side storage for mod settings' values (at this point - not necessarily connected to the particular Gogs instalaltion)
